### ISSUE TITLE
.net 6.0

### ISSUE THREAD

**Issue by trotor** [leonibr/efcore-snakecase#11]
I think your implementation doesn't work on .net 6.0. I use copy of your work from time it was not a library and struck on wall now. While searching for solution, found yours and for example 
Relational() has been missing since 3.0. Is there working copy somewhere?

**Comment by leonibr** [comment]
it is a different branch `master-v6`
the nuget is https://www.nuget.org/packages/Marques.EFCorev6.0.SnakeCase/

**Comment by trotor** [comment]
Okay, thanks!
